### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by markolipka** [Davidatlarge/REC_R#4]
At the moment providing the input of `test_case_2`, pre-processing and calling the function `calculate_con_rates_lin_sys_tichonov_mean_rate_2()` does produce a result, but it is obviously wrong.

**Comment by markolipka** [comment]
Would be helpful to have the original output of all intermediate steps for a simple test case (e.g. test_case_2)

**Comment by Davidatlarge** [comment]
The output was fixed by Karsten Lettmann finding a wrong matrix calculation and a missing input of boundary conditions
