### ISSUE TITLE
Generate output of function calculate_diff_operator_matrix_aequi_dist_grid_variable_coeff() with test data with original Matlab code

### ISSUE THREAD

**Issue by markolipka** [Davidatlarge/REC_R#5]
`calculate_diff_operator_matrix_aequi_dist_grid_variable_coeff()` could be tested with output of original Matlab-code available for certain edge-cases.

Output of test_case-scenario would be helpful to at least check if the function works in the simplest case as desired by the original author.

**Comment by markolipka** [comment]
the same for function `calculate_B_matrix()`

**Comment by markolipka** [comment]
same for `calculate_con_rates_lin_sys_tichonov_mean_rate_2()`

**Comment by markolipka** [comment]
@Davidatlarge would you take care for that? I don't have access to Matlab

**Comment by Davidatlarge** [comment]
not needed anymore
